# Generated by Django 4.2.16 on 2024-10-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='bio',
            field=models.TextField(verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='تلفن'),
        ),
    ]
