# Generated by Django 4.2.16 on 2024-10-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywork', '0002_alter_portfolioitem_image_alter_portfolioitem_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'نمونه  کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'رزومه', 'verbose_name_plural': 'رزومه'},
        ),
    ]
